---
#######################################
#######################################
## Translate Document GitHub Actions ##
#######################################
#######################################
name: Translate Document

#############################
# Start the job manually #
#############################
on: workflow_dispatch

permissions:
    id-token: write
    contents: read


jobs:
  ###################################
  # Upload source document to Azure #
  ###################################
  upload-source:
    runs-on: ubuntu-latest
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
      ##########################
      # Login to Azure         #
      ##########################
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: 'Run Azure CLI commands'
        run: |
            az account show
            az group list
            pwd 
  # translate:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: NPM Install
  #       run: npm install -g bats
  #     - name: BATS
  #       run: bats -v
  # download-all:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: NPM Install
  #       run: npm install -g bats
  #     - name: BATS
  #       run: bats -v
  # pull-request-all:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: NPM Install
  #       run: npm install -g bats
  #     - name: BATS
  #       run: bats -v
